File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\Tablet_analysis.py", line 159, in <module>
    main()
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\Tablet_analysis.py", line 141, in main
    gemini_analysis = analyze_tablet_data_with_gemini(cv_results, "Analyzed Zone")
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\Tablet_analysis.py", line 99, in analyze_tablet_data_with_gemini
    response = config.llm.predict(prompt)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\_api\deprecation.py", line 179, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\language_models\llms.py", line 1309, in predict
    return self(text, stop=_stop, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\_api\deprecation.py", line 179, in warning_emitting_wrapper
    return wrapped(*args, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\language_models\llms.py", line 1271, in __call__
    self.generate(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\language_models\llms.py", line 946, in generate
    output = self._generate_helper(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\language_models\llms.py", line 789, in _generate_helper
    raise e
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_core\language_models\llms.py", line 776, in _generate_helper
    self._generate(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_google_vertexai\llms.py", line 252, in _generate
    res = _completion_with_retry(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_google_vertexai\llms.py", line 71, in _completion_with_retry
    return _completion_with_retry_inner(prompt, is_gemini, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 376, in iter
    result = action(retry_state)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 185, in reraise
    raise self.last_attempt.result()
File "C:\Users\p00095189\Anaconda3\lib\concurrent\futures\_base.py", line 438, in result
    return self.__get_result()
File "C:\Users\p00095189\Anaconda3\lib\concurrent\futures\_base.py", line 390, in __get_result
    raise self._exception
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\tenacity\__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\langchain_google_vertexai\llms.py", line 59, in _completion_with_retry_inner
    return llm.client.generate_content(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\vertexai\generative_models\_generative_models.py", line 590, in generate_content
    return self._generate_content(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\vertexai\generative_models\_generative_models.py", line 705, in _generate_content
    gapic_response = self._prediction_client.generate_content(request=request)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\google\cloud\aiplatform_v1\services\prediction_service\client.py", line 2120, in generate_content
    response = rpc(
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\google\api_core\gapic_v1\method.py", line 131, in __call__
    return wrapped_func(*args, **kwargs)
File "C:\Users\p00095189\Desktop\WORK\Tablet_Analysis\ta_env\lib\site-packages\google\api_core\grpc_helpers.py", line 78, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
